# Generated by Django 4.2 on 2023-04-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
