# Generated by Django 4.2 on 2023-04-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0002_alter_genre_tmdb_id_alter_movie_overview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            (0, "Not known"),
                            (1, "Male"),
                            (2, "Female"),
                            (9, "Not applicable"),
                        ],
                        default=0,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovieCredit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("credits_type", models.CharField(max_length=255)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.person"
                    ),
                ),
            ],
        ),
    ]
