# Generated by Django 4.2 on 2023-04-15 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="person",
            table="people_person",
        ),
    ]
