# Generated by Django 4.2 on 2023-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_alter_person_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tmdb_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
