# Generated by Django 4.2 on 2023-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_person_tmdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviecredit",
            name="character",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="moviecredit",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="moviecredit",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="known_for_department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
