# Generated by Django 4.2 on 2023-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tmdb_id", models.BigIntegerField(null=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tmdb_id", models.BigIntegerField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("tagline", models.CharField(max_length=255, null=True)),
                ("language", models.CharField(max_length=15)),
                ("release_date", models.DateField()),
                ("runtime", models.IntegerField(null=True)),
                ("cinebase_rating", models.FloatField()),
                ("poster_path", models.CharField(max_length=255, null=True)),
                ("overview", models.TextField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("genres", models.ManyToManyField(to="movies.genre")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
